apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# The namespace (greeting-dev) is set by the apps ApplicationSet.
resources:
  - ../../base
images:
  - name: app
    newName: ghcr.io/camnoss/greeting
    newTag: "0c97c166bf1bf65b1a3b08bee77b45124d3f18be"
